- name: Adding users
  user:
    name: "guacamole"
    groups: ""
    append: yes
    shell: "/bin/bash"
    state: present
  with_items: "{{ create_users }}"
  register: users

# TODO: Make it so the guacamole user can't connect via ssh.
#- name: Expiring Passwords for new users (Linux)
#  command: "passwd -e {{ item.item }}"
#  with_items: "{{ users.results }}"
